//! Autogenerated weights for pallet_qor_identity
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI.
//! Manual changes will be overwritten.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions for pallet_qor_identity.
pub trait WeightInfo {
    fn register() -> Weight;
    fn link_account() -> Weight;
    fn unlink_account() -> Weight;
    fn add_attestation() -> Weight;
}

/// Default weights using RocksDB.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: QorIdentity AccountToIdentity (r:1 w:1)
    /// Storage: QorIdentity UsernameDiscriminators (r:1 w:1)
    /// Storage: QorIdentity Identities (r:0 w:1)
    /// Storage: QorIdentity TotalIdentities (r:1 w:1)
    /// Storage: System Account (r:1 w:1)
    fn register() -> Weight {
        Weight::from_parts(60_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(5))
    }

    /// Storage: QorIdentity AccountToIdentity (r:2 w:1)
    /// Storage: QorIdentity Identities (r:1 w:1)
    fn link_account() -> Weight {
        Weight::from_parts(45_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    /// Storage: QorIdentity AccountToIdentity (r:1 w:1)
    /// Storage: QorIdentity Identities (r:1 w:1)
    fn unlink_account() -> Weight {
        Weight::from_parts(40_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    /// Storage: QorIdentity Identities (r:1 w:1)
    fn add_attestation() -> Weight {
        Weight::from_parts(30_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

/// Default weights for testing.
impl WeightInfo for () {
    fn register() -> Weight {
        Weight::from_parts(60_000_000, 0)
    }

    fn link_account() -> Weight {
        Weight::from_parts(45_000_000, 0)
    }

    fn unlink_account() -> Weight {
        Weight::from_parts(40_000_000, 0)
    }

    fn add_attestation() -> Weight {
        Weight::from_parts(30_000_000, 0)
    }
}
