//! Autogenerated weights for pallet_cgt
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI.
//! Manual changes will be overwritten.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_cgt.
pub trait WeightInfo {
    fn transfer() -> Weight;
    fn burn() -> Weight;
}

/// Default weights for pallet_cgt using RocksDB.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: System Account (r:2 w:2)
    /// Storage: Cgt TotalBurned (r:1 w:1)
    /// Storage: Cgt CirculatingSupply (r:1 w:1)
    fn transfer() -> Weight {
        Weight::from_parts(50_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    /// Storage: System Account (r:1 w:1)
    /// Storage: Cgt TotalBurned (r:1 w:1)
    /// Storage: Cgt CirculatingSupply (r:1 w:1)
    fn burn() -> Weight {
        Weight::from_parts(40_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }
}

/// Default weights for testing.
impl WeightInfo for () {
    fn transfer() -> Weight {
        Weight::from_parts(50_000_000, 0)
    }

    fn burn() -> Weight {
        Weight::from_parts(40_000_000, 0)
    }
}
