# QOR Auth local infra — PostgreSQL + Redis via WSL (no Docker)
# Run from repo root: .\scripts\setup-qor-auth-infra.ps1
# Uses QOR_AUTH_WSL_DISTRO when set, otherwise the current WSL default distro

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
$QorAuthEnv = Join-Path $RepoRoot "services\qor-auth\.env"
$WslScript = Join-Path $RepoRoot "scripts\setup-qor-auth-wsl.sh"

function Get-WslDistro {
    if ($env:QOR_AUTH_WSL_DISTRO) {
        return $env:QOR_AUTH_WSL_DISTRO
    }

    function Strip-WslName([string]$Value) {
        if (-not $Value) { return $null }
        return ($Value -replace "`0", "").Trim()
    }

    $names = @()
    $raw = wsl -l -q 2>$null
    foreach ($line in $raw) {
        $name = Strip-WslName ([string]$line)
        if ($name -and $name -notmatch 'docker-desktop') {
            $names += $name
        }
    }
    if ($names.Count -gt 0) {
        return $names[0]
    }

    return "Ubuntu"
}

$WslDistro = Get-WslDistro

$DevPassword = "demiurge_qor_auth_dev"

function Write-QorAuthEnv {
    param([string]$DbUrl, [string]$RedisUrl)
    $content = @"
# Auto-generated by scripts/setup-qor-auth-infra.ps1 — local development only
RUN_ENV=development

QOR_AUTH__SERVER__HOST=0.0.0.0
QOR_AUTH__SERVER__PORT=8080

QOR_AUTH__DATABASE__URL=$DbUrl
QOR_AUTH__DATABASE__MAX_CONNECTIONS=10

QOR_AUTH__REDIS__URL=$RedisUrl

QOR_AUTH__JWT__ACCESS_SECRET=dev-access-secret-min-32-chars-qor-auth-local
QOR_AUTH__JWT__REFRESH_SECRET=dev-refresh-secret-min-32-chars-qor-auth-local
QOR_AUTH__JWT__ACCESS_EXPIRY_SECS=900
QOR_AUTH__JWT__REFRESH_EXPIRY_SECS=2592000
QOR_AUTH__JWT__ISSUER=qor-auth

QOR_AUTH__SECURITY__MAX_LOGIN_ATTEMPTS=5
QOR_AUTH__SECURITY__LOCKOUT_DURATION_SECS=900
QOR_AUTH__SECURITY__MAX_SESSIONS=10
QOR_AUTH__SECURITY__PASSWORD_MIN_LENGTH=12

SUBSTRATE_RPC_URL=ws://localhost:9944
"@
    Set-Content -Path $QorAuthEnv -Value $content -Encoding utf8
    Write-Host "Wrote $QorAuthEnv"
}

function Test-PortOpen {
    param([int]$Port)
    try {
        $tcp = New-Object System.Net.Sockets.TcpClient
        $tcp.Connect("127.0.0.1", $Port)
        $tcp.Close()
        return $true
    } catch { return $false }
}

if (-not (Get-Command wsl -ErrorAction SilentlyContinue)) {
    Write-Error "WSL is required. Install WSL and FedoraLinux-42, then re-run this script."
}

Write-Host "Starting QOR Auth infra in WSL ($WslDistro): PostgreSQL + Valkey (Redis)..."
$WslPath = ($WslScript -replace '\\', '/')
if ($WslPath -match '^([A-Za-z]):') {
    $drive = $Matches[1].ToLower()
    $WslPath = $WslPath -replace '^[A-Za-z]:', "/mnt/$drive"
}
wsl -d $WslDistro -e bash -c "export DEV_PASSWORD='$DevPassword'; bash '$WslPath'"

Start-Sleep -Seconds 2
if (-not (Test-PortOpen 5432)) { Write-Warning "PostgreSQL :5432 not reachable from Windows yet." }
if (-not (Test-PortOpen 6379)) { Write-Warning "Redis :6379 not reachable from Windows yet." }

$wslIp = & (Join-Path $RepoRoot "scripts\get-wsl-ip.ps1")
$dbHost = if ($wslIp) { $wslIp } else { "localhost" }
if ($wslIp) { Write-Host "WSL IP for QOR Auth: $wslIp" }
# Redis protected-mode only accepts loopback; use localhost from Windows (WSL port forward).
Write-QorAuthEnv "postgres://qor_auth:${DevPassword}@${dbHost}:5432/qor_auth" "redis://127.0.0.1:6379"
Write-Host "Ready. Postgres :5432, Redis :6379, QOR Auth listens on :8080"
Write-Host "Next: . .\scripts\env-rust-x.ps1  then  npm run qor-auth:run"
