# Start local Studio data-plane servers (Postgres + Valkey).
# Prefers Docker Compose. Falls back to WSL if Docker is unavailable.

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
$ComposeFile = Join-Path $RepoRoot "docker-compose.studio.yml"
$QorAuthEnv = Join-Path $RepoRoot "services\qor-auth\.env"
$DevPassword = "demiurge_qor_auth_dev"

function Test-PortOpen {
    param([int]$Port)
    try {
        $tcp = New-Object System.Net.Sockets.TcpClient
        $tcp.Connect("127.0.0.1", $Port)
        $tcp.Close()
        return $true
    } catch { return $false }
}

function Write-QorAuthEnv {
    param([string]$DbUrl, [string]$RedisUrl)
    $content = @"
# Auto-generated by scripts/start-studio-servers.ps1 — local development only
RUN_ENV=development

QOR_AUTH__SERVER__HOST=0.0.0.0
QOR_AUTH__SERVER__PORT=8080

QOR_AUTH__DATABASE__URL=$DbUrl
QOR_AUTH__DATABASE__MAX_CONNECTIONS=10

QOR_AUTH__REDIS__URL=$RedisUrl

QOR_AUTH__JWT__ACCESS_SECRET=dev-access-secret-min-32-chars-qor-auth-local
QOR_AUTH__JWT__REFRESH_SECRET=dev-refresh-secret-min-32-chars-qor-auth-local
QOR_AUTH__JWT__ACCESS_EXPIRY_SECS=900
QOR_AUTH__JWT__REFRESH_EXPIRY_SECS=2592000
QOR_AUTH__JWT__ISSUER=qor-auth

QOR_AUTH__SECURITY__MAX_LOGIN_ATTEMPTS=5
QOR_AUTH__SECURITY__LOCKOUT_DURATION_SECS=900
QOR_AUTH__SECURITY__MAX_SESSIONS=10
QOR_AUTH__SECURITY__PASSWORD_MIN_LENGTH=12

BLOCKCHAIN_RPC_URL=http://127.0.0.1:9944
"@
    Set-Content -Path $QorAuthEnv -Value $content -Encoding utf8
    Write-Host "Wrote $QorAuthEnv"
}

Write-Host "Starting Demiurge Studio servers (Pleroma local)..." -ForegroundColor Cyan

$dockerOk = $false
if (Get-Command docker -ErrorAction SilentlyContinue) {
    docker compose -f $ComposeFile up -d
    if ($LASTEXITCODE -eq 0) {
        $dockerOk = $true
        Write-Host "Docker Compose Studio servers are up." -ForegroundColor Green
    } else {
        Write-Warning "Docker Compose failed; falling back to WSL."
    }
}

if (-not $dockerOk) {
    & powershell -ExecutionPolicy Bypass -File (Join-Path $RepoRoot "scripts\setup-qor-auth-infra.ps1")
} else {
    $deadline = (Get-Date).AddSeconds(60)
    while ((Get-Date) -lt $deadline) {
        if ((Test-PortOpen 5432) -and (Test-PortOpen 6379)) { break }
        Start-Sleep -Seconds 2
    }
    Write-QorAuthEnv "postgres://qor_auth:${DevPassword}@127.0.0.1:5432/qor_auth" "redis://127.0.0.1:6379"
}

if (-not (Test-PortOpen 5432)) { Write-Warning "PostgreSQL :5432 not reachable yet." }
if (-not (Test-PortOpen 6379)) { Write-Warning "Valkey :6379 not reachable yet." }

Write-Host "Studio servers: Postgres :5432, Valkey :6379, qor-auth target :8080, node RPC :9944"
Write-Host "Next: npm run studio:start"
